# This file specifies metadata for each host.

[domains]
personal = "ibsenware.org"
personal_alt = "ulovlighacker.download"

[hosts.ahmed]
network = "rumpenettet"
ipv4Address = "192.168.68.222"

[hosts.ahmed.sshKeys]
linus = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKTV0NShiJXtHKtOk1kG28xvcSXww5LQTfCDued/Yog0 linus@ahmed"
root = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOodiSwTcZcaZxqLyHjI2MGe1CpIBvIzzbjpXrwAyiYO root@ahmed"

[hosts.ahmed.wireguard]
pubkey = "OyVax+rmBHEJsN3DmLAMEczO9mHwFDNb+D16cAV6TzM=" # Matches ./secrets/wireguard-vpn-key.age
port = 50000
ipv4Address = "77.33.188.139" # This is technically dynamic. Should use DDNS.

[hosts.muhammed]
network = "rumpenettet"
ipv4Address = "192.168.68.111"

[hosts.muhammed.sshKeys]
 linus = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcmUCfFA/arYpT0zBWoOXcyxN5bgk5cMrWgTIol5RsHB82VzoS+LG3IV4IwBz4QALaCj5DlhfbasGKMkFRgFvLerEtBleIb58RtOXIOf6TIUaqpyHB3h2CjdwrbmyjjWEl9W2BTpadrR5uPr0HoeED8dCFYE5cPjrSELtrYxEW0o1DBJw8bXfpgyYB21loBzrcOhRsrPSaS0gYHZLGY7Av7FGfncVZDLNYL0/pZ/t0UWD6JF+6FgOdGWAuuwSt5WR9DVxGilVG5aFktDB14fNPEBIVf7tkT4/McAihR/u344yaiUWA4bV7w039Ubhn9NdnoBSvGrP6jTy/zDgq5ywFj8aqcdlahxtELNWgxYYrI8HZzvITKo1FU7BOcUN1vNS4npOvyWBl7s3jFCO+R2E/BoyjfsjYTylacpepf26D87U32jNsh39OKdHxRF3/qmMGYa1L7N4M0iT9WFEMCcKB/MMAcHgE25vWPQaY1orU8X8NZPhxjfIVcw1rqcjwCryNwb1ZOMTIEc9kbGiP99MhE7ZA0yvHZfMezeymSwg1kN+iJDTp24gSsFtYuz5vm9lRu/PzfU9lNlp2KHdaLISUouSCCHPgF7zZSWtXa1B920zrAg2Fco8/Iymh+Fa0UNnrbnfyQTgLeNT12SLD4Y5gHimUsuq8tFkxjR6WffmrRw== linus@muhammed" 

[hosts.muhammed.wireguard]
pubkey =  "l0HoOpGEkyxG3dTsJ3+zNItD6bQEkzymGvcsMLFOdmA="

[hosts.ali]
network = "rumpenettet"
ipv4Address = "192.168.68.173"

[hosts.ali.sshKeys]
root = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHAINiNBU5XTF7E/ErI/xF9S/t350OR3sOIYhRhfAhZ2 root@ali"
linus = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMmjaik3g25rPFs1QD/Ig/tobACwHCDxkabc8x69yBZz linus@ali"

[networks.rumpenettet]
v4 = "192.168.68.0"
